import { useState } from 'react'
import { apiRequest } from '../lib/api'
import type { Farm } from '../types'
export default function Farms() {
  const [farms, setFarms] = useState<Farm[]>([]); const [name, setName] = useState(''); const [district, setDistrict] = useState('Kanpur Nagar'); const [state, setState] = useState('Uttar Pradesh'); const [area, setArea] = useState('1'); const [error, setError] = useState('')
  const load = async () => { try { setError(''); setFarms(await apiRequest<Farm[]>('/farms')) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load farms') } }
  const create = async () => { try { setError(''); const farm = await apiRequest<Farm>('/farms', { method:'POST', body:JSON.stringify({name, district, state, area:Number(area), unit:'acre'}) }); setFarms(items => [...items, farm]); setName('') } catch (e) { setError(e instanceof Error ? e.message : 'Unable to create farm') } }
  return <div className="space-y-5"><div><h1 className="text-2xl font-bold">Your farms</h1><p className="mt-1 text-sm text-[#566154]">Only your farms are shown here.</p></div><div className="grid gap-3 rounded-2xl bg-white p-4 ring-1 ring-black/5 sm:grid-cols-4"><input aria-label="Farm name" value={name} onChange={e=>setName(e.target.value)} placeholder="Farm name" className="min-h-11 rounded-xl border px-3"/><input aria-label="District" value={district} onChange={e=>setDistrict(e.target.value)} className="min-h-11 rounded-xl border px-3"/><input aria-label="Area" type="number" min="0.01" value={area} onChange={e=>setArea(e.target.value)} className="min-h-11 rounded-xl border px-3"/><button onClick={create} disabled={name.trim().length<2} className="min-h-11 rounded-xl bg-[#166534] px-4 font-semibold text-white disabled:opacity-50">Add farm</button></div>{error && <p role="alert" className="rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}<button onClick={load} className="min-h-11 rounded-xl border bg-white px-4 font-semibold">Load farms</button><div className="grid gap-3">{farms.map(f=><article key={f.id} className="rounded-2xl bg-white p-4 ring-1 ring-black/5"><h2 className="font-semibold">{f.name}</h2><p className="text-sm text-[#566154]">{f.district}, {f.state} · {f.area} {f.unit}</p></article>)}{!farms.length && <p className="text-sm text-[#566154]">No farms loaded yet.</p>}</div></div>
}
