import {useEffect,useMemo,useState} from 'react'
import {BrowserRouter,useLocation,useNavigate} from 'react-router-dom'
import {Leaf,CloudRain,Sprout,ShieldAlert,Store,MessageCircle,Home as HomeIcon,LandPlot,BarChart3,MoreHorizontal,LogOut,RefreshCw,CheckCircle2,AlertTriangle} from 'lucide-react'
import {supabase} from './lib/supabase'
import {apiRequest} from './lib/api'
import type {Dashboard,Farm} from './types'

const demo:Dashboard={farm:{id:'demo-farm',name:'Kanpur Wheat Farm',district:'Kanpur Nagar',state:'Uttar Pradesh',area:5,unit:'acre'},crop:{name:'Wheat',growth_stage:'vegetative',area:5},decision:{id:'demo-no-irrigation',title:'Avoid irrigation today',priority:'high',why:'Rain probability is 85% and soil moisture is already 72%.',evidence:['Rain probability: 85%','Soil moisture: 72%','Wheat: vegetative stage'],valid_until:new Date(Date.now()+86400000).toISOString(),state:'active'},weather:{current_temp_c:27,rain_probability:85,humidity:78,wind_kph:12,stale:false,impact:'Rain is likely today; avoid unnecessary irrigation and monitor drainage.',forecast:[]},soil:{moisture:72,ph:6.8,nitrogen:120,phosphorus:45,potassium:160,moisture_status:'High',freshness:'recent'},risk:{overall_score:.68,weather_score:.79,disease_score:.42,pest_score:.31,confidence:'medium-high',factors:[{factor:'High rain probability',effect:'increases field moisture and weather-related risk',score:.79},{factor:'Soil moisture 72%',effect:'irrigation demand is low today',score:.72}],disclaimer:'Risk scores are decision-support signals, not diagnoses.'},market:{commodity:'Wheat',market:'Kanpur Mandi',forecast_low:2470,forecast_high:2550,trend:'slightly rising',signal:'Watch / compare offers',confidence:'medium',disclaimer:'Forecast is an estimate, not a guaranteed selling price.',history:[2420,2440,2410,2460,2485,2470,2495]}}

function App(){
 const [lang,setLang]=useState<'en'|'hi'>('en'); const [demoMode,setDemoMode]=useState(!supabase); const [farms,setFarms]=useState<Farm[]>([]); const [selectedFarm,setSelectedFarm]=useState('demo-farm'); const [dash,setDash]=useState<Dashboard>(demo); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [tab,setTab]=useState('Home'); const [advisor,setAdvisor]=useState(''); const [answer,setAnswer]=useState(''); const nav=useNavigate(); const loc=useLocation()
 const t=useMemo(()=>lang==='hi'?{home:'होम',farm:'खेत',insights:'जानकारी',adv:'सलाहकार',more:'और',decision:'आज का खेत निर्णय',weather:'मौसम',soil:'मिट्टी',risk:'फसल जोखिम',market:'मंडी',why:'क्यों?',ask:'कृषि मित्र से पूछें',send:'पूछें',refresh:'डेटा ताज़ा करें',setup:'अपना खेत जोड़ें'}:{home:'Home',farm:'Farm',insights:'Insights',adv:'Advisor',more:'More',decision:"Today's farm decision",weather:'Weather',soil:'Soil',risk:'Crop risk',market:'Market',why:'Why?',ask:'Ask KrishiMitra',send:'Ask',refresh:'Refresh data',setup:'Add your farm'},[lang])
 const load=async()=>{setLoading(true);setError('');try{if(!demoMode){const fs=await apiRequest<Farm[]>('/farms');setFarms(fs);const id=selectedFarm==='demo-farm'?fs[0]?.id:selectedFarm;if(id){setSelectedFarm(id);setDash(await apiRequest<Dashboard>(`/farms/${id}/dashboard`))}}else{await new Promise(r=>setTimeout(r,350));setDash({...demo,decision:{...demo.decision,valid_until:new Date(Date.now()+86400000).toISOString()}})}}catch(e){setError(e instanceof Error?e.message:'Unable to refresh data')}finally{setLoading(false)}}
 useEffect(()=>{if(!demoMode)load()},[demoMode])
 const ask=async()=>{if(!advisor.trim())return;setAnswer('');try{if(demoMode){setAnswer(lang==='hi'?'आज सिंचाई न करना बेहतर है। बारिश की संभावना 85% और मिट्टी की नमी 72% है। बारिश के बाद गेहूं की फसल की निगरानी करें।':'Avoid irrigation today. Rain probability is 85% and soil moisture is 72%. Monitor the wheat crop after rainfall.')}else{const r=await apiRequest<any>(`/farms/${selectedFarm}/advisor`,{method:'POST',body:JSON.stringify({message:advisor,language:lang}),idempotencyKey:crypto.randomUUID()});setAnswer(r.answer)}}catch(e){setAnswer(e instanceof Error?e.message:'Unable to get advice')}}
 const signOut=async()=>{await supabase?.auth.signOut();setDemoMode(true);setTab('Home');nav('/')}
 const card=(icon:any,title:string,value:string,detail:string)=><article className="rounded-2xl bg-white p-4 ring-1 ring-black/5"><div className="flex items-center gap-2"><span className="rounded-xl bg-[#F8FAF7] p-2 text-[#166534]">{icon}</span><p className="font-semibold">{title}</p></div><p className="mt-4 text-xl font-bold">{value}</p><p className="mt-1 text-sm text-[#566154]">{detail}</p></article>
 return <div className="min-h-screen bg-[#F8FAF7] text-[#172016]">
  <header className="sticky top-0 z-10 border-b border-black/5 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-5xl items-center justify-between px-4 py-3"><button onClick={()=>setTab('Home')} className="flex items-center gap-2"><Leaf className="text-[#166534]"/><span><b className="text-[#166534]">KrishiMitra AI</b><small className="block text-xs text-[#566154]">Predict. Advise. Act.</small></span></button><div className="flex items-center gap-2"><button onClick={()=>setLang(lang==='en'?'hi':'en')} className="min-h-11 rounded-xl border px-3 text-sm font-semibold">{lang==='en'?'हिन्दी':'English'}</button><button onClick={signOut} className="min-h-11 rounded-xl border px-3" aria-label="Sign out"><LogOut size={18}/></button></div></div></header>
  <main className="mx-auto max-w-5xl px-4 py-5 pb-28">
   {error&&<div role="alert" className="mb-4 flex gap-2 rounded-xl bg-red-50 p-3 text-sm text-red-800"><AlertTriangle size={18}/>{error}</div>}
   <div className="mb-5 flex items-center justify-between"><div><p className="text-sm font-semibold uppercase tracking-wide text-[#166534]">{t.decision}</p><h1 className="mt-1 text-2xl font-bold">{dash.farm.name}</h1><p className="text-sm text-[#566154]">{dash.farm.district}, {dash.farm.state} · {dash.crop.name} · {dash.crop.growth_stage}</p></div><button onClick={load} className="min-h-11 rounded-xl border bg-white px-3" aria-label={t.refresh}><RefreshCw size={18} className={loading?'animate-spin':''}/></button></div>
   {tab==='Home'&&<>
    <section className="mb-5 rounded-2xl bg-white p-5 shadow-sm ring-1 ring-black/5"><div className="flex items-start gap-3"><div className="rounded-xl bg-[#166534] p-2 text-white"><CheckCircle2/></div><div className="flex-1"><span className="text-xs font-bold uppercase text-[#166534]">{dash.decision.priority} priority</span><h2 className="mt-1 text-2xl font-bold">{dash.decision.title}</h2><p className="mt-2 text-[#566154]">{dash.decision.why}</p><div className="mt-4 flex flex-wrap gap-2">{dash.decision.evidence.map(x=><span key={x} className="rounded-full bg-[#F8FAF7] px-3 py-1 text-xs font-medium">{x}</span>)}</div></div></div></section>
    <section className="grid grid-cols-2 gap-3 md:grid-cols-4">{card(<CloudRain size={19}/>,t.weather,`${dash.weather.rain_probability}% rain`,`${dash.weather.current_temp_c}°C · ${dash.weather.humidity}% humidity`)}{card(<Sprout size={19}/>,t.soil,`${dash.soil.moisture}% moisture`,`pH ${dash.soil.ph} · ${dash.soil.freshness}`)}{card(<ShieldAlert size={19}/>,t.risk,`${Math.round(dash.risk.overall_score*100)}% risk`,`${dash.risk.confidence} confidence`)}{card(<Store size={19}/>,t.market,`₹${dash.market.forecast_low}–₹${dash.market.forecast_high}`,`${dash.market.trend} · ${dash.market.confidence}`)}</section>
    <section className="mt-5 rounded-2xl bg-white p-5 ring-1 ring-black/5"><h2 className="font-bold">{t.why}</h2><ul className="mt-3 space-y-2 text-sm text-[#566154]">{dash.risk.factors.map((f:any)=><li key={f.factor}><b className="text-[#172016]">{f.factor}:</b> {f.effect}</li>)}</ul><p className="mt-3 text-xs text-[#566154]">{dash.risk.disclaimer}</p></section>
   </>}
   {tab==='Farm'&&<FarmPanel demoMode={demoMode} farms={farms} onDemo={()=>setDemoMode(true)}/>} 
   {tab==='Insights'&&<div className="space-y-4"><section className="rounded-2xl bg-white p-5 ring-1 ring-black/5"><h2 className="font-bold">{t.weather}</h2><p className="mt-2">Rain probability <b>{dash.weather.rain_probability}%</b>; {dash.weather.impact}</p><div className="mt-4 grid grid-cols-3 gap-2 text-center text-sm"><div className="rounded-xl bg-[#F8FAF7] p-3"><b>{dash.weather.current_temp_c}°C</b><small className="block text-[#566154]">Temperature</small></div><div className="rounded-xl bg-[#F8FAF7] p-3"><b>{dash.weather.humidity}%</b><small className="block text-[#566154]">Humidity</small></div><div className="rounded-xl bg-[#F8FAF7] p-3"><b>{dash.weather.wind_kph}</b><small className="block text-[#566154]">km/h wind</small></div></div></section><section className="rounded-2xl bg-white p-5 ring-1 ring-black/5"><h2 className="font-bold">{t.soil}</h2><div className="mt-3 grid grid-cols-2 gap-3 text-sm md:grid-cols-4">{[['Moisture',dash.soil.moisture+'%'],['pH',dash.soil.ph],['N',dash.soil.nitrogen],['P',dash.soil.phosphorus],['K',dash.soil.potassium]].map(([a,b])=><div key={String(a)} className="rounded-xl border p-3"><span className="text-[#566154]">{a}</span><b className="mt-1 block">{b}</b></div>)}</div></section><section className="rounded-2xl bg-white p-5 ring-1 ring-black/5"><h2 className="font-bold">{t.market}</h2><p className="mt-2 text-sm">{dash.market.market}: <b>₹{dash.market.forecast_low}–₹{dash.market.forecast_high}/quintal</b></p><p className="mt-1 text-sm text-[#566154]">{dash.market.signal} · {dash.market.confidence} confidence.</p><p className="mt-3 text-xs text-[#566154]">{dash.market.disclaimer}</p></section></div>}
   {tab==='Advisor'&&<section className="rounded-2xl bg-white p-5 ring-1 ring-black/5"><h2 className="text-xl font-bold">{t.ask}</h2><p className="mt-1 text-sm text-[#566154]">Ask about this farm; answers use the available farm context.</p><textarea value={advisor} onChange={e=>setAdvisor(e.target.value)} className="mt-4 min-h-28 w-full rounded-xl border p-3" placeholder={lang==='hi'?'आज गेहूं के लिए क्या करूँ?':'What should I do for my wheat today?'}/><button onClick={ask} className="mt-3 min-h-11 rounded-xl bg-[#166534] px-5 font-semibold text-white">{t.send}</button>{answer&&<div className="mt-4 rounded-xl bg-[#F8FAF7] p-4 text-sm leading-6">{answer}<p className="mt-3 text-xs text-[#566154]">Source: KrishiMitra approved rules/knowledge · decision support, not diagnosis.</p></div>}</section>}
   {tab==='More'&&<section className="space-y-3"><div className="rounded-2xl bg-white p-5 ring-1 ring-black/5"><h2 className="font-bold">KrishiMitra AI</h2><p className="mt-2 text-sm text-[#566154]">One Farm. One AI. One Decision.</p><p className="mt-4 text-sm">Language: {lang==='en'?'English':'Hindi'}</p><p className="mt-1 text-sm">Mode: {demoMode?'Seeded demo':'Connected Supabase'}</p></div><div className="rounded-2xl bg-white p-5 ring-1 ring-black/5 text-sm">Forecasts are estimates. Risk signals are not diagnoses. For pesticide choice or disease diagnosis, consult qualified local agricultural support and approved product labels.</div></section>}
  </main>
  <nav aria-label="Primary" className="fixed inset-x-0 bottom-0 z-10 border-t border-black/5 bg-white/95 backdrop-blur"><div className="mx-auto grid max-w-5xl grid-cols-5 px-2 py-2">{[[t.home,'Home',HomeIcon],[t.farm,'Farm',LandPlot],[t.insights,'Insights',BarChart3],[t.adv,'Advisor',MessageCircle],[t.more,'More',MoreHorizontal]].map(([label,key,I]:any)=><button key={key} onClick={()=>setTab(key)} className={`min-h-12 rounded-xl text-xs font-medium ${tab===key?'bg-[#F8FAF7] text-[#166534]':''}`}><I className="mx-auto mb-1" size={19}/>{label}</button>)}</div></nav>
 </div>
}
function FarmPanel({demoMode,farms,onDemo}:{demoMode:boolean;farms:Farm[];onDemo:()=>void}){return <section className="space-y-4"><div className="rounded-2xl bg-white p-5 ring-1 ring-black/5"><h2 className="text-xl font-bold">Your farms</h2><p className="mt-1 text-sm text-[#566154]">Only your farm context is used for decisions.</p></div>{demoMode?<div className="rounded-2xl bg-white p-5 ring-1 ring-black/5"><h3 className="font-bold">Kanpur Wheat Farm</h3><p className="mt-1 text-sm text-[#566154]">Kanpur Nagar, Uttar Pradesh · 5 acres · Loam</p><p className="mt-3 rounded-xl bg-[#F8FAF7] p-3 text-sm">Seeded demo data: wheat, vegetative stage, soil moisture 72%.</p></div>:farms.map(f=><div key={f.id} className="rounded-2xl bg-white p-5 ring-1 ring-black/5"><b>{f.name}</b><p className="text-sm text-[#566154]">{f.district}, {f.state} · {f.area} {f.unit}</p></div>)}{!demoMode&&!farms.length&&<button onClick={onDemo} className="min-h-11 rounded-xl border px-4">Use seeded demo</button>}</section>}
export default function Root(){return <BrowserRouter><App/></BrowserRouter>}
